### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by luebken** [giantswarm/giantswarm-firstapp-php#3]

**Comment by advanderveer** [comment]
description of what? #4 ?

**Comment by ZeissS** [comment]
Inception! I guess he means the repository itself could get a description.

**Comment by advanderveer** [comment]
Ah, roger. A user with 'owner' permissions will need to do this (I'm not allowd), for copy and paste needs:
```
A simple PHP app with a Redis cache demonstrating Docker and Giant Swarm
```

**Comment by ZeissS** [comment]
Done.
