### ISSUE TITLE
Copy and adapt Readme

### ISSUE THREAD

**Issue by luebken** [giantswarm/giantswarm-firstapp-php#4]
https://github.com/giantswarm/giantswarm-firstapp-nodejs/blob/master/README.md

**Comment by advanderveer** [comment]
Just uploaded the adapted README, i've changed some of the wording and added `make docker-build` step which will be needed if the user didn't publish and image to his registry. Please review!

**Comment by luebken** [comment]
In the other repos we use the old domain to reflect the purpose of the app:
>            "currentweather-$username.gigantic.io": "1337"
https://github.com/giantswarm/giantswarm-currentweather-go/blob/master/swarm.json#L18
https://github.com/giantswarm/giantswarm-firstapp-nodejs/blob/master/swarm.json#L18

Please use the same scheme. We can consider changing it in all repos afterwards.
